const $=s=>document.querySelector(s);const fmt=n=>Number(n||0).toLocaleString('pt-BR');const pct=n=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const PARTY_COLORS={"PT":"#C62828","PL":"#184E8A","UNIÃO":"#008C95","PP":"#4A54A8","MDB":"#2E7D32","PSD":"#7A5C00","PSDB":"#0077B6","REPUBLICANOS":"#5B3C88","PSB":"#B56A00","PDT":"#AD1457","PODE":"#3569B7","SOLIDARIEDADE":"#6A3D9A","SDD":"#6A3D9A","PSOL":"#D4A000","NOVO":"#8C6D1F","CIDADANIA":"#9B4D5F","AVANTE":"#006B6B","PV":"#3E8E41","REDE":"#5AAE61"};
const OFFICES={gov:'Governador',sen:'Senado',depf:'Deputado federal',depe:'Deputado estadual',pres:'Presidente'};const SEATS_2022={gov:1,sen:1,depf:8,depe:24},SEATS_2026={gov:1,sen:2,depf:8,depe:24};
const ELECTED_2022={gov:{PT:1},sen:{PL:1},depf:{PL:4,PT:2,'UNIÃO':2},depe:{PSDB:10,PT:3,PV:3,PL:3,SOLIDARIEDADE:2,'UNIÃO':2,MDB:1}};
let hist=null,live=null,selectedFindingId=null;
function partyColor(p){return PARTY_COLORS[String(p||'').toUpperCase()]||'#777f86'}
function aggregate2022(office){if(!hist)return[];const cargo={gov:'Governador',sen:'Senador',depf:'Deputado Federal',depe:'Deputado Estadual',pres:'Presidente'}[office];const by=new Map();Object.values(hist.municipios||{}).forEach(m=>(m?.['1']?.[cargo]||[]).forEach(x=>{const k=x.nome+'|'+x.partido,e=by.get(k)||{name:x.nome,party:x.partido,votes:0};e.votes+=Number(x.votos||0);by.set(k,e)}));return [...by.values()].sort((a,b)=>b.votes-a.votes)}
function party2022(office){if(!hist)return[];const cargo={depf:'Deputado Federal',depe:'Deputado Estadual',sen:'Senador'}[office];if(cargo){const by=new Map();Object.values(hist.partidos||{}).forEach(m=>(m?.['1']?.[cargo]||[]).forEach(x=>{const e=by.get(x.partido)||{party:x.partido,votes:0};e.votes+=Number(x.votos||0);by.set(x.partido,e)}));return [...by.values()].sort((a,b)=>b.votes-a.votes)}const by=new Map();aggregate2022(office).forEach(x=>{const e=by.get(x.party)||{party:x.party,votes:0};e.votes+=x.votes;by.set(x.party,e)});return [...by.values()].sort((a,b)=>b.votes-a.votes)}
function renderStatus(){const prog=Number(live?.progress||0);$('#progressValue').textContent=pct(prog);$('#progressBar').style.width=Math.min(100,prog)+'%';if(live?.status==='live'||live?.status==='final'){$('#statusTitle').textContent=live.status==='final'?'Totalização concluída':'Apuração 2026 em andamento';$('#statusText').textContent=(live.message||'Dados oficiais carregados.')+' Última geração: '+(live.source_generated_at||live.generated_at||'—')+'.';$('#liveStripText').textContent=live.status==='final'?'Resultado oficial consolidado para comparação':'Comparação atualizada durante a apuração';$('#liveStamp').textContent=live.source_generated_at||live.generated_at||''}else{$('#statusTitle').textContent='Preparado para a apuração';$('#statusText').textContent=live?.message||'Os dados de 2022 já estão disponíveis. A camada de 2026 será preenchida automaticamente com a divulgação oficial do TSE.'}}
function renderParnamirim(){const p=live?.parnamirim;if(!p||!p.candidates?.length)return;const lead=p.candidates[0],second=p.candidates[1];$('#parnamirimCompare').innerHTML='<span><b>2022</b><strong>Bolsonaro</strong><small>53,67% · 2º turno</small></span><span><b>2026 · '+pct(p.progress)+'</b><strong>'+lead.name+'</strong><small>'+pct(lead.pct)+(second?' · +'+pct(lead.pct-second.pct):'')+'</small></span>';$('#parnamirimText').textContent=p.final?'Resultado municipal finalizado pelo TSE. Comparação histórica pronta para publicação.':'Acompanhamento provisório durante a totalização municipal. O resultado pode mudar.'}
function renderFindings(){const office=$('#findingOffice').value,type=$('#findingType').value;const rows=(live?.findings||[]).filter(x=>x.office===office&&(type==='all'||x.type===type));const box=$('#findings');if(!rows.length){box.innerHTML='<article class="card empty"><b>Aguardando achados para este filtro.</b><span>Os detectores só usam dados oficiais disponíveis e identificam se o achado ainda é provisório.</span></article>';return}box.innerHTML=rows.slice(0,18).map(x=>'<article class="card finding"><span class="tag">'+String(x.type_label||x.type).toUpperCase()+'</span><h3>'+x.headline+'</h3><span class="value">'+(x.display_value||'')+'</span><p>'+x.summary+'</p><span class="state '+(x.confirmed?'confirmed':'')+'">'+(x.confirmed?'CONFIRMADO':'PROVISÓRIO · '+pct(x.progress||0))+'</span><div class="publish-finding"><button class="publish-finding" data-finding="'+x.id+'">Gerar publicação</button></div></article>').join('');box.querySelectorAll('button[data-finding]').forEach(b=>b.onclick=()=>selectFinding(b.dataset.finding,true));renderPublisherOptions()}
function renderParties(){const office=$('#partyOffice').value,h=party2022(office),l=live?.offices?.[office]?.parties||[];const map=new Map();h.forEach(x=>map.set(x.party,{party:x.party,v22:x.votes,v26:0}));l.forEach(x=>{const e=map.get(x.party)||{party:x.party,v22:0,v26:0};e.v26=Number(x.votes||0);map.set(x.party,e)});const rows=[...map.values()].sort((a,b)=>(b.v26||b.v22)-(a.v26||a.v22));const total22=rows.reduce((s,x)=>s+x.v22,0),total26=rows.reduce((s,x)=>s+x.v26,0);$('#partyRows').innerHTML=rows.length?rows.map(x=>{const p22=total22?x.v22/total22*100:0,p26=total26?x.v26/total26*100:0,d=total26?p26-p22:null;return '<div class="party-row"><div class="party-name"><i class="party-dot" style="background:'+partyColor(x.party)+'"></i>'+x.party+'</div><div class="vote-cell"><strong>'+fmt(x.v22)+'</strong><small>'+pct(p22)+'</small></div><div class="vote-cell"><strong>'+(total26?fmt(x.v26):'—')+'</strong><small>'+(total26?pct(p26):'aguardando')+'</small></div><div class="delta '+(d===null?'muted':'')+'">'+(d===null?'—':(d>=0?'+':'')+d.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+' p.p.')+'</div></div>'}).join(''):'<div class="loading">Sem dados para este cargo.</div>';const prop=['depf','depe'].includes(office);$('#partyMethod').textContent=prop?'Deputados: votos válidos do partido = votos nominais válidos + votos válidos de legenda. A variação compara a participação do partido no total computado de cada ano.':'Cargo majoritário: os votos das candidaturas são agrupados por partido. A variação compara a participação no total computado de cada ano.'}
function renderOfficeCompare(){const box=$('#officeCompare');box.innerHTML=['gov','sen','depf','depe'].map(o=>{const c22=aggregate2022(o).length,c26=live?.offices?.[o]?.candidates_with_votes||0,e26=live?.offices?.[o]?.elected||0,prog=live?.offices?.[o]?.progress||0;return '<article class="card office-card"><span class="kicker">'+OFFICES[o].toUpperCase()+'</span><h3>'+SEATS_2022[o]+' vaga'+(SEATS_2022[o]>1?'s':'')+' no RN em 2022</h3><div class="year-pair"><div><b>2022</b><strong>'+SEATS_2022[o]+'</strong><small>eleito'+(SEATS_2022[o]>1?'s':'')+' · '+c22+' candidaturas com votos</small></div><div><b>2026</b><strong>'+(live?.status==='waiting'?'—':e26)+'</strong><small>eleitos informados · '+(c26||'—')+' com votos</small></div></div><p class="footnote">2026: '+pct(prog)+' das seções. Para deputados, a situação de eleito depende da totalização proporcional oficial.</p></article>'}).join('');renderElectedParties()}
function renderElectedParties(){const o=$('#electedOffice').value,a=ELECTED_2022[o]||{},b={};(live?.offices?.[o]?.elected_by_party||[]).forEach(x=>b[x.party]=x.count);const parties=[...new Set([...Object.keys(a),...Object.keys(b)])].sort((x,y)=>(b[y]||a[y]||0)-(b[x]||a[x]||0));$('#electedPartyRows').innerHTML=parties.length?parties.map(p=>'<div class="elected-row"><strong><i class="party-dot" style="display:inline-block;margin-right:7px;background:'+partyColor(p)+'"></i>'+p+'</strong><span>2022 · '+(a[p]||0)+'</span><span>2026 · '+(live?.status==='waiting'?'—':(b[p]||0))+'</span></div>').join(''):'<div class="loading">Aguardando composição.</div>'}
async function load(){try{const [h,l]=await Promise.all([fetch('rn2022-results.json',{cache:'no-store'}).then(r=>r.json()),fetch('data/achados-2026.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)]);hist=h;live=l||{status:'waiting',progress:0,findings:[],offices:{}};renderAll()}catch(e){console.error(e);$('#statusTitle').textContent='Base histórica indisponível';$('#statusText').textContent='Não foi possível carregar a base de 2022. Nenhum dado foi substituído por simulação.'}}
function renderAll(){renderStatus();renderParnamirim();renderFindings();renderParties();renderOfficeCompare();renderPublisherOptions()}
$('#findingOffice').onchange=renderFindings;$('#publishFinding').onchange=e=>selectFinding(e.target.value,false);$('#copyFindingText').onclick=copyFindingText;$('#copyFindingImage').onclick=copyFindingImage;$('#openFindingX').onclick=openFindingX;$('#shareFinding').onclick=shareFinding;$('#downloadFindingImage').onclick=downloadFindingImage;$('#findingType').onchange=renderFindings;$('#partyOffice').onchange=renderParties;$('#electedOffice').onchange=renderElectedParties;window.addEventListener('scroll',()=>$('#toTop').classList.toggle('show',scrollY>500));$('#toTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});load();setInterval(async()=>{try{const r=await fetch('data/achados-2026.json?ts='+Date.now(),{cache:'no-store'});if(r.ok){live=await r.json();renderAll()}}catch{}},60000);
function allFindings(){return live?.findings||[]}
function findingById(id){return allFindings().find(x=>x.id===id)}
function escText(s){return String(s||'').replace(/\s+/g,' ').trim()}
function buildFindingText(x){
 if(!x)return 'Aguardando um achado oficial de 2026.';
 const state=x.confirmed?'Resultado confirmado pelo TSE.':'Dado provisório com '+pct(x.progress||0)+' da totalização considerada. O cenário pode mudar.';
 return escText(x.headline)+'.\n\n'+escText(x.summary)+'\n\n'+state+'\n\nFonte: Tribunal Superior Eleitoral.\n\n#Eleições2026 #RN';
}
function wrapCanvas(ctx,text,maxWidth){
 const words=String(text||'').split(/\s+/),lines=[];let line='';
 for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}
 if(line)lines.push(line);return lines
}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawFinding(x){
 const cv=$('#findingCanvas');if(!cv)return;const ctx=cv.getContext('2d');ctx.clearRect(0,0,1080,1080);ctx.fillStyle='#f4efe5';ctx.fillRect(0,0,1080,1080);
 ctx.fillStyle='#17191c';ctx.fillRect(0,0,1080,116);ctx.fillStyle='#f5c400';ctx.fillRect(64,55,155,8);
 ctx.fillStyle='#fff';ctx.font='700 30px Inter, Arial';ctx.fillText('UEFY · ACHADOS 2026',64,48);ctx.font='500 22px Inter, Arial';ctx.fillStyle='#d7d7d7';ctx.fillText('Rio Grande do Norte · comparação 2022 × 2026',64,91);
 if(!x){ctx.fillStyle='#17191c';ctx.font='700 58px Inter, Arial';ctx.fillText('Aguardando achados',64,270);ctx.font='400 30px Inter, Arial';ctx.fillStyle='#626970';ctx.fillText('A publicação será gerada a partir dos dados oficiais do TSE.',64,325);return}
 ctx.fillStyle='#17191c';ctx.font='800 24px Inter, Arial';ctx.fillText(String(x.type_label||x.type).toUpperCase(),64,184);
 ctx.font='700 64px Inter, Arial';let y=270;for(const line of wrapCanvas(ctx,x.headline,930).slice(0,4)){ctx.fillText(line,64,y);y+=72}
 if(x.display_value){ctx.fillStyle='#f5c400';roundRect(ctx,64,y+16,Math.min(900,ctx.measureText(x.display_value).width+54),86,12);ctx.fillStyle='#17191c';ctx.font='800 42px Inter, Arial';ctx.fillText(x.display_value,91,y+73);y+=130}
 ctx.fillStyle='#4f555b';ctx.font='400 30px Inter, Arial';for(const line of wrapCanvas(ctx,x.summary,930).slice(0,6)){ctx.fillText(line,64,y);y+=42}
 ctx.fillStyle=x.confirmed?'#f5c400':'#ded8cc';roundRect(ctx,64,890,360,58,29);ctx.fillStyle='#17191c';ctx.font='800 21px Inter, Arial';ctx.fillText(x.confirmed?'CONFIRMADO PELO TSE':'PROVISÓRIO · '+pct(x.progress||0),91,927);
 ctx.fillStyle='#626970';ctx.font='500 21px Inter, Arial';ctx.fillText('Fonte: Tribunal Superior Eleitoral',64,1012);ctx.textAlign='right';ctx.fillStyle='#17191c';ctx.font='800 24px Inter, Arial';ctx.fillText('UEFY',1016,1012);ctx.textAlign='left';
}
function renderPublisherOptions(){
 const sel=$('#publishFinding');if(!sel)return;const rows=allFindings();const old=selectedFindingId;
 sel.innerHTML=rows.length?rows.map(x=>'<option value="'+x.id+'">'+escText(x.headline)+'</option>').join(''):'<option value="">Aguardando achados de 2026</option>';
 if(rows.length){selectedFindingId=rows.some(x=>x.id===old)?old:rows[0].id;sel.value=selectedFindingId}else selectedFindingId=null;
 renderPublisher();
}
function renderPublisher(){const x=findingById(selectedFindingId);drawFinding(x);const ta=$('#findingPostText');if(ta)ta.value=buildFindingText(x)}
function selectFinding(id,scroll){selectedFindingId=id;const sel=$('#publishFinding');if(sel)sel.value=id;renderPublisher();if(scroll)$('#publicar')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function canvasBlob(){return new Promise(r=>$('#findingCanvas').toBlob(r,'image/png'))}
async function copyFindingText(){const t=$('#findingPostText').value;try{await navigator.clipboard.writeText(t)}catch{}}
async function copyFindingImage(){try{const b=await canvasBlob();await navigator.clipboard.write([new ClipboardItem({'image/png':b})])}catch{downloadFindingImage()}}
async function downloadFindingImage(){const b=await canvasBlob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='uefy-achados-2026.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function openFindingX(){const t=$('#findingPostText').value;try{await copyFindingImage();await navigator.clipboard.writeText(t)}catch{}window.open('https://x.com/compose/post?text='+encodeURIComponent(t),'_blank','noopener')}
async function shareFinding(){const t=$('#findingPostText').value,b=await canvasBlob(),file=new File([b],'uefy-achados-2026.png',{type:'image/png'});if(navigator.share){try{if(navigator.canShare?.({files:[file]}))await navigator.share({text:t,files:[file]});else await navigator.share({text:t});return}catch(e){if(e?.name==='AbortError')return}}await copyFindingText();downloadFindingImage()}
